from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='joy',
            executable='joy_node',
            name='joy_node',
        ),
        Node(
            package='rov2026',
            executable='joy_to_move',
            name='joy_to_move_node',
        ),
        Node(
            package='rov2026',
            executable='rov_controller',
            name='rov_controller_node',
        ),        
        Node(
            package='rov2026',
            executable='thrusters_mixer',
            name='thrusters_mixer_node',
        ),
        Node(
            package='rov2026',
            executable='rov_input',
            name='rov_input_node',
        ),
        Node(
            package='rov2026',
            executable='ros_to_esp',
            name='ros_to_esp_node',
        ),
        Node(
           package='rov2026',
           executable='gripper_controller',
           name='gripper_controller',
        ),
        Node(
            package='rov2026',
            executable='esp_commands_control',
            name='esp_commands_control_node',
        ),
        Node(
            package='rov2026',
            executable='esp_to_ros',
            name='EspToRos',
        ),
        Node(
            package='rov2026',
            executable='pid_handler',
            name='pid_handler',
        ),
        Node(
            package='rov2026',
            executable='rov_flags',
            name='flags',
        ),
    ])