#=================================================Network Default Settings====================================================
DEFAULT_SSID = "Torpedo_Float"
DEFAULT_ESP_IP = "192.168.4.1"
DEFAULT_PORT = 1234
BUFFER_SIZE = 1024
RESET_DURATION = 1
PACKET_SIZE = 3
DEPTH_INDEX = 1
TIME_INDEX = 0
MAX_TIMOUT_COUNT = 5
CONNECTION_TIMEOUT_DURATION = 3
