; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:black_f407ze]
platform = ststm32
board = black_f407ze
framework = arduino
lib_deps = stm32duino/STM32duino FreeRTOS@^10.3.3

[env:genericSTM32F401CD]
platform = ststm32
board = genericSTM32F401CD
framework = arduino
upload_protocol = stlink
lib_deps = stm32duino/STM32duino FreeRTOS@^10.3.3

